
function BullingStor()
{

    {/* ليست وهمية */}
    const dataBulling = [
        {
            "firstName": "James",
            "lastName": "Butt",
            "company": "Benton John B Jr",
            "address": "6649 N Blue Gum St",
            "city": "New Orleans",
            "county": "Orleans",
            "state": "LA",
            "zip": "70116",
            "phone1": "504-621-8927",
            "phone2": "504-845-1427",
            "email": "jbutt@gmail.com",
            "website": "http://www.bentonjohnbjr.com",
            "type": "Lead",
            "projects_count": "16",
            "date": "14-Jun-20",
            "status":"approved"
            
        },
        {
            "firstName": "Josephine",
            "lastName": "Darakjy",
            "company": "Chanay Jeffrey A Esq",
            "address": "4 B Blue Ridge Blvd",
            "city": "Brighton",
            "county": "Livingston",
            "state": "MI",
            "zip": "48116",
            "phone1": "810-292-9388",
            "phone2": "810-374-9840",
            "email": "josephine_darakjy@darakjy.org",
            "website": "http://www.chanayjeffreyaesq.com",
            "type": "Lead",
            "projects_count": "6",
            "date": "23-Jun-22",
            "status":"approved"
        },
        {
            "firstName": "Art",
            "lastName": "Venere",
            "company": "Chemel James L Cpa",
            "address": "8 W Cerritos Ave #54",
            "city": "Bridgeport",
            "county": "Gloucester",
            "state": "NJ",
            "zip": "8014",
            "phone1": "856-636-8749",
            "phone2": "856-264-4130",
            "email": "art@venere.org",
            "website": "http://www.chemeljameslcpa.com",
            "type": "Customer",
            "projects_count": "6",
            "date": "22-Sep-20",
            "status":"approved"
        },
        {
            "firstName": "Lenna",
            "lastName": "Paprocki",
            "company": "Feltz Printing Service",
            "address": "639 Main St",
            "city": "Anchorage",
            "county": "Anchorage",
            "state": "AK",
            "zip": "99501",
            "phone1": "907-385-4412",
            "phone2": "907-921-2010",
            "email": "lpaprocki@hotmail.com",
            "website": "http://www.feltzprintingservice.com",
            "type": "Customer",
            "projects_count": "3",
            "date": "13-Oct-22",
            "status":"approved"
        },
        {
            "firstName": "Donette",
            "lastName": "Foller",
            "company": "Printing Dimensions",
            "address": "34 Center St",
            "city": "Hamilton",
            "county": "Butler",
            "state": "OH",
            "zip": "45011",
            "phone1": "513-570-1893",
            "phone2": "513-549-4561",
            "email": "donette.foller@cox.net",
            "website": "http://www.printingdimensions.com",
            "type": "Lead",
            "projects_count": "5",
            "date": "13-Jul-22",
            "status":"approved"
        },
        {
            "firstName": "Simona",
            "lastName": "Morasca",
            "company": "Chapman Ross E Esq",
            "address": "3 Mcauley Dr",
            "city": "Ashland",
            "county": "Ashland",
            "state": "OH",
            "zip": "44805",
            "phone1": "419-503-2484",
            "phone2": "419-800-6759",
            "email": "simona@morasca.com",
            "website": "http://www.chapmanrosseesq.com",
            "type": "Lead",
            "projects_count": "16",
            "date": "12-Jun-22",
            "status":"approved"
        },
        {
            "firstName": "Mitsue",
            "lastName": "Tollner",
            "company": "Morlong Associates",
            "address": "7 Eads St",
            "city": "Chicago",
            "county": "Cook",
            "state": "IL",
            "zip": "60632",
            "phone1": "773-573-6914",
            "phone2": "773-924-8565",
            "email": "mitsue_tollner@yahoo.com",
            "website": "http://www.morlongassociates.com",
            "type": "Lead",
            "projects_count": "11",
            "date": "28-Jul-20",
            "status":"approved"
        },
        {
            "firstName": "Leota",
            "lastName": "Dilliard",
            "company": "Commercial Press",
            "address": "7 W Jackson Blvd",
            "city": "San Jose",
            "county": "Santa Clara",
            "state": "CA",
            "zip": "95111",
            "phone1": "408-752-3500",
            "phone2": "408-813-1105",
            "email": "leota@hotmail.com",
            "website": "http://www.commercialpress.com",
            "type": "Lead",
            "projects_count": "9",
            "date": "06-Aug-20",
            "status":"approved"
        },
        {
            "firstName": "Sage",
            "lastName": "Wieser",
            "company": "Truhlar And Truhlar Attys",
            "address": "5 Boston Ave #88",
            "city": "Sioux Falls",
            "county": "Minnehaha",
            "state": "SD",
            "zip": "57105",
            "phone1": "605-414-2147",
            "phone2": "605-794-4895",
            "email": "sage_wieser@cox.net",
            "website": "http://www.truhlarandtruhlarattys.com",
            "type": "Customer",
            "projects_count": "13",
            "date": "12-Oct-20",
            "status":"approved"
        },
        {
            "firstName": "Kris",
            "lastName": "Marrier",
            "company": "King Christopher A Esq",
            "address": "228 Runamuck Pl #2808",
            "city": "Baltimore",
            "county": "Baltimore City",
            "state": "MD",
            "zip": "21224",
            "phone1": "410-655-8723",
            "phone2": "410-804-4694",
            "email": "kris@gmail.com",
            "website": "http://www.kingchristopheraesq.com",
            "type": "Customer",
            "projects_count": "14",
            "date": "29-Jan-21",
            "status":"accepted"
        },
        {
            "firstName": "Minna",
            "lastName": "Amigon",
            "company": "Dorl James J Esq",
            "address": "2371 Jerrold Ave",
            "city": "Kulpsville",
            "county": "Montgomery",
            "state": "PA",
            "zip": "19443",
            "phone1": "215-874-1229",
            "phone2": "215-422-8694",
            "email": "minna_amigon@yahoo.com",
            "website": "http://www.dorljamesjesq.com",
            "type": "Lead",
            "projects_count": "9",
            "date": "07-Oct-20",
            "status":"accepted"
        },
        {
            "firstName": "Abel",
            "lastName": "Maclead",
            "company": "Rangoni Of Florence",
            "address": "37275 St  Rt 17m M",
            "city": "Middle Island",
            "county": "Suffolk",
            "state": "NY",
            "zip": "11953",
            "phone1": "631-335-3414",
            "phone2": "631-677-3675",
            "email": "amaclead@gmail.com",
            "website": "http://www.rangoniofflorence.com",
            "type": "Lead",
            "projects_count": "15",
            "date": "29-Aug-21",
            "status":"accepted"
        },
        {
            "firstName": "Kiley",
            "lastName": "Caldarera",
            "company": "Feiner Bros",
            "address": "25 E 75th St #69",
            "city": "Los Angeles",
            "county": "Los Angeles",
            "state": "CA",
            "zip": "90034",
            "phone1": "310-498-5651",
            "phone2": "310-254-3084",
            "email": "kiley.caldarera@aol.com",
            "website": "http://www.feinerbros.com",
            "type": "Lead",
            "projects_count": "11",
            "date": "15-Nov-21",
            "status":"accepted"
        },
        {
            "firstName": "Graciela",
            "lastName": "Ruta",
            "company": "Buckley Miller & Wright",
            "address": "98 Connecticut Ave Nw",
            "city": "Chagrin Falls",
            "county": "Geauga",
            "state": "OH",
            "zip": "44023",
            "phone1": "440-780-8425",
            "phone2": "440-579-7763",
            "email": "gruta@cox.net",
            "website": "http://www.buckleymillerwright.com",
            "type": "Customer",
            "projects_count": "16",
            "date": "29-Sep-21",
            "status":"accepted"
        },
        {
            "firstName": "Cammy",
            "lastName": "Albares",
            "company": "Rousseaux Michael Esq",
            "address": "56 E Morehead St",
            "city": "Laredo",
            "county": "Webb",
            "state": "TX",
            "zip": "78045",
            "phone1": "956-537-6195",
            "phone2": "956-841-7216",
            "email": "calbares@gmail.com",
            "website": "http://www.rousseauxmichaelesq.com",
            "type": "Lead",
            "projects_count": "9",
            "date": "03-Mar-20",
            "status":"approved"
        },
        {
            "firstName": "Mattie",
            "lastName": "Poquette",
            "company": "Century Communications",
            "address": "73 State Road 434 E",
            "city": "Phoenix",
            "county": "Maricopa",
            "state": "AZ",
            "zip": "85013",
            "phone1": "602-277-4385",
            "phone2": "602-953-6360",
            "email": "mattie@aol.com",
            "website": "http://www.centurycommunications.com",
            "type": "Lead",
            "projects_count": "3",
            "date": "04-Dec-21",
            "status":"reject"
        },
        {
            "firstName": "Meaghan",
            "lastName": "Garufi",
            "company": "Bolton Wilbur Esq",
            "address": "69734 E Carrillo St",
            "city": "Mc Minnville",
            "county": "Warren",
            "state": "TN",
            "zip": "37110",
            "phone1": "931-313-9635",
            "phone2": "931-235-7959",
            "email": "meaghan@hotmail.com",
            "website": "http://www.boltonwilburesq.com",
            "type": "Lead",
            "projects_count": "2",
            "date": "03-Feb-21",
            "status":"reject"
        },
        {
            "firstName": "Gladys",
            "lastName": "Rim",
            "company": "T M Byxbee Company Pc",
            "address": "322 New Horizon Blvd",
            "city": "Milwaukee",
            "county": "Milwaukee",
            "state": "WI",
            "zip": "53207",
            "phone1": "414-661-9598",
            "phone2": "414-377-2880",
            "email": "gladys.rim@rim.org",
            "website": "http://www.tmbyxbeecompanypc.com",
            "type": "Customer",
            "projects_count": "9",
            "date": "25-Jul-22",
            "status":"reject"
        },
        {
            "firstName": "Yuki",
            "lastName": "Whobrey",
            "company": "Farmers Insurance Group",
            "address": "1 State Route 27",
            "city": "Taylor",
            "county": "Wayne",
            "state": "MI",
            "zip": "48180",
            "phone1": "313-288-7937",
            "phone2": "313-341-4470",
            "email": "yuki_whobrey@aol.com",
            "website": "http://www.farmersinsurancegroup.com",
            "type": "Lead",
            "projects_count": "5",
            "date": "24-Apr-20",
            "status":"reject"
        },
        {
            "firstName": "Fletcher",
            "lastName": "Flosi",
            "company": "Post Box Services Plus",
            "address": "394 Manchester Blvd",
            "city": "Rockford",
            "county": "Winnebago",
            "state": "IL",
            "zip": "61109",
            "phone1": "815-828-2147",
            "phone2": "815-426-5657",
            "email": "fletcher.flosi@yahoo.com",
            "website": "http://www.postboxservicesplus.com",
            "type": "Lead",
            "projects_count": "10",
            "date": "29-Jul-21",
            "status":"reject"
        },
        {
            "firstName": "Bette",
            "lastName": "Nicka",
            "company": "Sport En Art",
            "address": "6 S 33rd St",
            "city": "Aston",
            "county": "Delaware",
            "state": "PA",
            "zip": "19014",
            "phone1": "610-545-3615",
            "phone2": "610-492-4643",
            "email": "bette_nicka@cox.net",
            "website": "http://www.sportenart.com",
            "type": "Lead",
            "projects_count": "5",
            "date": "16-Jan-20",
            "status":"reject"
        },
        {
            "firstName": "Veronika",
            "lastName": "Inouye",
            "company": "C 4 Network Inc",
            "address": "6 Greenleaf Ave",
            "city": "San Jose",
            "county": "Santa Clara",
            "state": "CA",
            "zip": "95111",
            "phone1": "408-540-1785",
            "phone2": "408-813-4592",
            "email": "vinouye@aol.com",
            "website": "http://www.cnetworkinc.com",
            "type": "Customer",
            "projects_count": "4",
            "date": "11-Sep-21",
            "status":"reject"
        },
        {
            "firstName": "Willard",
            "lastName": "Kolmetz",
            "company": "Ingalls Donald R Esq",
            "address": "618 W Yakima Ave",
            "city": "Irving",
            "county": "Dallas",
            "state": "TX",
            "zip": "75062",
            "phone1": "972-303-9197",
            "phone2": "972-896-4882",
            "email": "willard@hotmail.com",
            "website": "http://www.ingallsdonaldresq.com",
            "type": "Customer",
            "projects_count": "11",
            "date": "21-Jun-22",
            "status":"reject"
        },
        {
            "firstName": "Maryann",
            "lastName": "Royster",
            "company": "Franklin Peter L Esq",
            "address": "74 S Westgate St",
            "city": "Albany",
            "county": "Albany",
            "state": "NY",
            "zip": "12204",
            "phone1": "518-966-7987",
            "phone2": "518-448-8982",
            "email": "mroyster@royster.com",
            "website": "http://www.franklinpeterlesq.com",
            "type": "Customer",
            "projects_count": "11",
            "date": "06-Nov-21",
            "status":"reject"
        },
        {
            "firstName": "Alisha",
            "lastName": "Slusarski",
            "company": "Wtlz Power 107 Fm",
            "address": "3273 State St",
            "city": "Middlesex",
            "county": "Middlesex",
            "state": "NJ",
            "zip": "8846",
            "phone1": "732-658-3154",
            "phone2": "732-635-3453",
            "email": "alisha@slusarski.com",
            "website": "http://www.wtlzpowerfm.com",
            "type": "Customer",
            "projects_count": "15",
            "date": "13-Dec-21",
            "status":"reject"
        }
    ];
    let copydataBulling =[];
    {/* عملية التأكد و وضعها في ليست أخرى  */}
    for ( let i= 0 ; i < dataBulling.length ; i++ )
    {
        if (dataBulling[i].status == "accepted"||dataBulling[i].status == "approved")
        {
            copydataBulling.push(dataBulling[i]);
        }
    }
    {/* طباعة الليست الي فيها المطلوب  */}
    for ( let i = 0 ; i < copydataBulling.length; i++)
    {
        console.log(copydataBulling[i]);
    }
    {/* بضل علي أخذ الليست من اقزيح و تمريرها لعبدالرحمن */}
    
}

export default BullingStor ;